import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'

const resources = {
  ru: {
    translation: {
      dashboard: { title: 'Дашборд агента', subtitle: 'Сводная информация о работе ИИ-агента в реальном времени', export: 'Скачать отчёт (PDF)', kpi: { companies: 'Найдено компаний', conversion: 'Конверсия писем', meetings: 'Назначено встреч', projects: 'Проектов в каталоге' }, charts: { conversionTitle: 'Конверсия писем по месяцам (%)' }, activity: { title: 'Последняя активность', empty: 'Активности пока нет.', emptySub: 'Начните с верификации компаний.' }, logs: { title: 'Журнал действий агента', empty: 'Журнал пуст. Агент ожидает действий.' } },
      analysis: { title: 'Анализ индустрии и компетенций', subtitle: 'Фаза 1. Сравнение учебной программы с требованиями рынка', approve: 'Утвердить стратегию', profileTitle: 'Профиль компетенций', gapTitle: 'Разрыв компетенций (Gap Analysis)', detailsTitle: 'Детализация по навыкам', skill: 'Навык', demand: 'Востребованность', inProgram: 'В программе', trend: 'Тренд', growing: 'Растёт', stable: 'Стабильно', alert: { title: 'Критическая точка эскалации №1', message: 'Агент обнаружил значительный разрыв в компетенциях ML/AI и NLP (разрыв >50%). Пожалуйста, утвердите приоритетную область поиска партнеров или скорректируйте программу.', approveBtn: 'Утвердить приоритет: IT & ML', adjustBtn: 'Скорректировать программу' }, artifact: { title: 'Артефакт: Стратегический Профиль Партнера', industry: 'Приоритетная отрасль', skills: 'Ключевые навыки', niche: 'Нишевые компетенции', region: 'Регион поиска' } },
      companies: { title: 'Формирование пула компаний', subtitle: 'Фаза 2. Поиск релевантных индустриальных партнеров', top100: 'Топ-100 компаний', verify: 'Верифицировать шорт-лист', search: 'Поиск компании...', export: 'Экспорт отчёта', filters: { size: 'Все размеры', region: 'Все регионы', stack: 'Любой стек' }, table: { company: 'Компания', industry: 'Отрасль', scoring: 'Скоринг соответствия', region: 'Регион', status: 'Статус', actions: 'Действия' } },
      communications: { title: 'CRM — Управление коммуникациями', subtitle: 'Фазы 3 и 4. Генерация писем и ведение воронки', tone: 'Тон коммуникации:', formal: 'Формальный', informal: 'Неформальный', model: 'Модель:', export: 'Экспорт отчёта', generateMaterials: 'Партнерский пакет (PDF)', columns: { draft: 'Черновики', sent: 'Отправлено', interest: 'Есть интерес', rejected: 'Отказ', meeting: 'Назначена встреча' }, actions: { generate: 'Генерация', interest: 'Интерес', reject: 'Отказ', meeting: 'Встреча', reaction: 'Реакция:' }, letter: { title: 'Редактирование письма', recipient: 'Получатель:', label: 'Текст письма', close: 'Закрыть', send: 'Отправить письмо' } },
      projects: { title: 'Каталог проектов для студентов', subtitle: 'Фаза 5. Управление сгенерированными техническими заданиями', export: 'Экспорт каталога', roles: 'РОЛИ', competencies: 'КОМПЕТЕНЦИИ', technologies: 'ТЕХНОЛОГИИ', viewTZ: 'Просмотреть ТЗ', publish: 'Опубликовать', published: 'Опубликовано', uploading: 'Отправка в LMS...', uploadSuccess: 'Данные успешно отправлены в LMS ПроКомпетенции', empty: { title: 'Каталог пуст', message: 'Проекты появляются автоматически после назначения встречи с компанией.', tip: '💡 Подсказка: Перейдите в "Коммуникации" → найдите карточку в "Отправлено" → нажмите "Интерес" → "Встреча"' }, tzModal: { title: 'Техническое задание', info: 'Агент сгенерировал структуру на основе соглашения с партнёром. Вы можете отредактировать текст перед публикацией для студентов.', close: 'Закрыть', save: 'Сохранить изменения' } },
      memory: { title: 'Память агента (RFT / NARS)', subtitle: 'Визуализация когнитивных связей и реляционной памяти', structure: 'Структура памяти', companies: 'Компании', skills: 'Навыки', connections: 'Связи', legend: 'Легенда', company: 'Компания', skill: 'Навык', competency: 'Компетенция', howItWorks: { title: 'Как это работает?', message: 'Агент строит граф связей на основе действий. Узлы притягиваются связанными элементами и отталкиваются друг от друга.', hint: '🖱️ Перетаскивайте для панорамирования, колёсико для зума' } },
      settings: { title: 'Настройки', subtitle: 'Конфигурация профиля и параметров ИИ-агента', profile: 'Профиль пользователя', agent: 'Настройки ИИ-агента', org: 'Учебное заведение', notifications: 'Уведомления', save: 'Сохранить настройки' },
      common: { export: 'Экспорт', cancel: 'Отмена', save: 'Сохранить', loading: 'Загрузка...', close: 'Закрыть', confirm: 'Подтвердить', delete: 'Удалить', edit: 'Редактировать' },
      nav: { dashboard: 'Дашборд', analysis: 'Анализ компетенций', companies: 'Поиск компаний', communications: 'Коммуникации', projects: 'Каталог проектов', memory: 'Память агента', settings: 'Настройки' },
      industries: { "IT": "IT", "Финансы": "Финансы", Телеком: "Телеком", Промышленность: "Промышленность", Финтех: "Финтех", "E-commerce": "E-commerce", "IT/Безопасность": "IT/Безопасность" },
      regions: { Москва: "Москва", Екатеринбург: "Екатеринбург" },
      statuses: { Активный: "Активный", Ожидание: "Ожидание", Новый: "Новый" },
      notifications: { title: "Уведомления", markAllRead: "Прочитать все", empty: "Нет новых уведомлений", types: { escalation: "Эскалация", followup: "Фоллоу-ап", response: "Ответ", system: "Система" }, msgs: { esc1: "Обнаружен разрыв в компетенциях ML/AI. Требуется утверждение стратегии.", esc2: "Шорт-лист верифицирован. Готов к генерации писем.", esc3: "Письмо для {{company}} готово к отправке. Требуется проверка.", esc4: "Получен ответ от {{company}}. Требуется личная встреча.", followup: "Пора отправить фоллоу-ап для {{company}} (День {{day}}).", meeting: "Встреча с {{company}} назначена. Проект сгенерирован.", verified: "Успешно добавлено {{count}} компаний в CRM." } },
      meeting: { modal: { title: "Фиксация результатов переговоров", summaryLabel: "Итоги встречи / Договоренности", summaryPlaceholder: "Опишите ключевые договоренности с партнером...", agreementLabel: "Текст соглашения (черновик)", agreementPlaceholder: "Вставьте текст соглашения или ссылку на документ...", confirmBtn: "Сохранить и назначить встречу", successMsg: "Соглашение зафиксировано, проект создан." } }
    }
  },
  en: {
    translation: {
      dashboard: { title: 'Agent Dashboard', subtitle: 'AI Agent performance overview in real-time', export: 'Download Report (PDF)', kpi: { companies: 'Companies found', conversion: 'Email conversion', meetings: 'Meetings scheduled', projects: 'Projects in catalog' }, charts: { conversionTitle: 'Email conversion by month (%)' }, activity: { title: 'Recent activity', empty: 'No activity yet.', emptySub: 'Start by verifying companies.' }, logs: { title: 'Agent action log', empty: 'Log is empty. Agent is waiting for actions.' } },
      analysis: { title: 'Industry and Competency Analysis', subtitle: 'Phase 1. Comparing curriculum with market requirements', approve: 'Approve Strategy', profileTitle: 'Competency Profile', gapTitle: 'Competency Gap Analysis', detailsTitle: 'Skill Details', skill: 'Skill', demand: 'Demand', inProgram: 'In Program', trend: 'Trend', growing: 'Growing', stable: 'Stable', alert: { title: 'Escalation Point #1', message: 'Agent detected significant gap in ML/AI and NLP competencies (gap >50%). Please approve priority partner search area or adjust the program.', approveBtn: 'Approve Priority: IT & ML', adjustBtn: 'Adjust Program' }, artifact: { title: 'Artifact: Strategic Partner Profile', industry: 'Priority Industry', skills: 'Key Skills', niche: 'Niche Competencies', region: 'Search Region' } },
      companies: { title: 'Company Pool Formation', subtitle: 'Phase 2. Finding relevant industry partners', top100: 'Top-100 Companies', verify: 'Verify Shortlist', search: 'Search company...', export: 'Export Report', filters: { size: 'All sizes', region: 'All regions', stack: 'Any stack' }, table: { company: 'Company', industry: 'Industry', scoring: 'Matching Score', region: 'Region', status: 'Status', actions: 'Actions' } },
      communications: { title: 'CRM — Communication Management', subtitle: 'Phases 3 & 4. Letter generation and pipeline management', tone: 'Communication tone:', formal: 'Formal', informal: 'Informal', model: 'Model:', export: 'Export Report', generateMaterials: 'Partner Pack (PDF)', columns: { draft: 'Drafts', sent: 'Sent', interest: 'Interest', rejected: 'Rejected', meeting: 'Meeting Scheduled' }, actions: { generate: 'Generate', interest: 'Interest', reject: 'Reject', meeting: 'Meeting', reaction: 'Reaction:' }, letter: { title: 'Edit Letter', recipient: 'Recipient:', label: 'Letter text', close: 'Close', send: 'Send Letter' } },
      projects: { title: 'Student Project Catalog', subtitle: 'Phase 5. Managing generated technical specifications', export: 'Export Catalog', roles: 'ROLES', competencies: 'COMPETENCIES', technologies: 'TECHNOLOGIES', viewTZ: 'View Specification', publish: 'Publish', published: 'Published', uploading: 'Uploading to LMS...', uploadSuccess: 'Data successfully sent to LMS ProCompetencies', empty: { title: 'Catalog is empty', message: 'Projects appear automatically after scheduling a meeting with a company.', tip: '💡 Tip: Go to "Communications" → find card in "Sent" → click "Interest" → "Meeting"' }, tzModal: { title: 'Technical Specification', info: 'Agent generated structure based on partner agreement. You can edit the text before publishing to students.', close: 'Close', save: 'Save Changes' } },
      memory: { title: 'Agent Memory (RFT / NARS)', subtitle: 'Visualization of cognitive connections and relational memory', structure: 'Memory Structure', companies: 'Companies', skills: 'Skills', connections: 'Connections', legend: 'Legend', company: 'Company', skill: 'Skill', competency: 'Competency', howItWorks: { title: 'How it works?', message: 'Agent builds connection graph based on actions. Nodes attract connected elements and repel each other.', hint: '🖱️ Drag to pan, scroll to zoom' } },
      settings: { title: 'Settings', subtitle: 'Profile and AI Agent configuration', profile: 'User Profile', agent: 'AI Agent Settings', org: 'Educational Institution', notifications: 'Notifications', save: 'Save Settings' },
      common: { export: 'Export', cancel: 'Cancel', save: 'Save', loading: 'Loading...', close: 'Close', confirm: 'Confirm', delete: 'Delete', edit: 'Edit' },
      nav: { dashboard: 'Dashboard', analysis: 'Competency Analysis', companies: 'Company Search', communications: 'Communications', projects: 'Project Catalog', memory: 'Agent Memory', settings: 'Settings' },
      industries: { "IT": "IT", "Финансы": "Finance", Телеком: "Telecom", Промышленность: "Industry", Финтех: "Fintech", "E-commerce": "E-commerce", "IT/Безопасность": "IT/Security" },
      regions: { Москва: "Moscow", Екатеринбург: "Yekaterinburg" },
      statuses: { Активный: "Active", Ожидание: "Pending", Новый: "New" },
      notifications: { title: "Notifications", markAllRead: "Mark all as read", empty: "No new notifications", types: { escalation: "Escalation", followup: "Follow-up", response: "Response", system: "System" }, msgs: { esc1: "Gap detected in ML/AI competencies. Strategy approval required.", esc2: "Shortlist verified. Ready for letter generation.", esc3: "Letter for {{company}} ready. Requires review.", esc4: "Response received from {{company}}. Meeting required.", followup: "Time to send follow-up to {{company}} (Day {{day}}).", meeting: "Meeting with {{company}} scheduled. Project generated.", verified: "Successfully added {{count}} companies to CRM." } },
      meeting: { modal: { title: "Save Negotiation Results", summaryLabel: "Meeting Summary / Agreements", summaryPlaceholder: "Describe key agreements with the partner...", agreementLabel: "Agreement Text (Draft)", agreementPlaceholder: "Paste agreement text or document link...", confirmBtn: "Save & Schedule Meeting", successMsg: "Agreement saved, project created." } }
    }
  }
}

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'ru',
    interpolation: { escapeValue: false },
    detection: { order: ['localStorage', 'navigator'], caches: ['localStorage'] },
    debug: false
  })

export default i18n