import { useState } from 'react'
import { useProjects } from '@/hooks/useProjects'
import { Card } from '@/components/ui/Card'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { Modal } from '@/components/ui/Modal'
import { Eye, Send, TrendingUp, CheckCircle2, FolderOpen, Download, FileText, Loader2 } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { exportProjectsReport } from '@/lib/export'

export default function Projects() {
  const { t, i18n } = useTranslation()
  const locale = i18n.language
  
  // Используем хук для получения данных из API
  const { projects, isLoading, publish, isPublishing } = useProjects()
  
  const [selectedTz, setSelectedTz] = useState<number | null>(null)
  const [tzContent, setTzContent] = useState('')
  const [isTzModalOpen, setIsTzModalOpen] = useState(false)

  const handleOpenTz = (project: any) => {
    setSelectedTz(project.id)
    setTzContent(project.tz_content || (locale === 'ru' ? 'ТЗ генерируется агентом...' : 'TZ is being generated by agent...'))
    setIsTzModalOpen(true)
  }

  const handleSaveTz = () => {
    if (selectedTz) {
      // TODO: API call to save TZ if needed
      setIsTzModalOpen(false)
    }
  }

  const complexityColors: Record<string, string> = {
    'easy': 'bg-green-100 text-green-700',
    'medium': 'bg-yellow-100 text-yellow-700',
    'hard': 'bg-red-100 text-red-700'
  }

  const statusColors: Record<string, 'success' | 'info' | 'default'> = {
    'product': 'success',
    'research': 'info',
    'educational': 'default'
  }

  const getComplexityLabel = (complexity: string) => {
    const labels: Record<string, string> = {
      easy: locale === 'ru' ? 'Лёгкий' : 'Easy',
      medium: locale === 'ru' ? 'Средний' : 'Medium',
      hard: locale === 'ru' ? 'Сложный' : 'Hard'
    }
    return labels[complexity] || complexity
  }

  const getStatusLabel = (status: string) => {
    const labels: Record<string, string> = {
      product: locale === 'ru' ? 'Продуктовый' : 'Product',
      research: locale === 'ru' ? 'Исследовательский' : 'Research',
      educational: locale === 'ru' ? 'Учебный' : 'Educational'
    }
    return labels[status] || status
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-[60vh] text-text-secondary">
        <Loader2 className="animate-spin mr-2" /> {t('common.loading')}
      </div>
    )
  }

  if (projects.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] text-center">
        <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
          <FolderOpen size={32} className="text-text-secondary" />
        </div>
        <h2 className="text-xl font-bold text-text-primary">{t('projects.empty.title')}</h2>
        <p className="text-text-secondary mt-2 max-w-md">{t('projects.empty.message')}</p>
        <div className="mt-4 p-3 bg-blue-50 rounded-lg text-sm text-blue-700 border border-blue-200">
          {t('projects.empty.tip')}
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-2xl font-bold text-text-primary">{t('projects.title')}</h1>
          <p className="text-text-secondary mt-1">{t('projects.subtitle')}</p>
        </div>
        <Button variant="secondary" size="sm" onClick={() => exportProjectsReport()}>
          <Download size={16} className="mr-2" />
          {t('projects.export')}
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {projects.map((project) => (
          <Card key={project.id} className="flex flex-col">
            <div className="flex justify-between items-start mb-3">
              <Badge variant={statusColors[project.status] || 'default'}>
                {getStatusLabel(project.status)}
              </Badge>
              <span className={`text-xs px-2 py-1 rounded-full ${complexityColors[project.complexity] || 'bg-slate-100 text-slate-700'}`}>
                {getComplexityLabel(project.complexity)}
              </span>
            </div>

            <h3 className="font-bold text-lg text-text-primary mb-2">{project.title || (locale === 'ru' ? 'Без названия' : 'Untitled')}</h3>
            <p className="text-sm text-text-secondary mb-4 flex items-center gap-1">
              <TrendingUp size={14} />
              {project.partner || (locale === 'ru' ? 'Партнёр не указан' : 'Partner not specified')}
            </p>

            <div className="space-y-3 flex-1">
              <div>
                <p className="text-xs font-semibold text-text-secondary mb-1">{t('projects.roles')}</p>
                <div className="flex flex-wrap gap-1">
                  {(project.roles || [locale === 'ru' ? 'Разработчик' : 'Developer']).map((role: string) => (
                    <span key={role} className="text-xs bg-slate-100 text-text-secondary px-2 py-0.5 rounded">
                      {role}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <p className="text-xs font-semibold text-text-secondary mb-1">{t('projects.competencies')}</p>
                <div className="flex flex-wrap gap-1">
                  {(project.competencies || ['Python']).map((comp: string) => (
                    <span key={comp} className="text-xs bg-blue-50 text-primary px-2 py-0.5 rounded">
                      {comp}
                    </span>
                  ))}
                </div>
              </div>

              {project.technologies && project.technologies.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-text-secondary mb-1">{t('projects.technologies')}</p>
                  <div className="flex flex-wrap gap-1">
                    {project.technologies.map((tech: string) => (
                      <span key={tech} className="text-xs bg-purple-50 text-purple-700 px-2 py-0.5 rounded">
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>

            <div className="flex gap-2 mt-4 pt-4 border-t border-border">
              <Button variant="secondary" size="sm" className="flex-1" onClick={() => handleOpenTz(project)}>
                <FileText size={14} className="mr-1" />
                {t('projects.viewTZ')}
              </Button>
              
              <Button 
                size="sm" 
                className="flex-1"
                onClick={() => publish(project.id)}
                disabled={isPublishing || project.is_published}
              >
                {isPublishing ? (
                  <>
                    <Loader2 size={14} className="mr-2 animate-spin" />
                    {t('projects.uploading')}
                  </>
                ) : project.is_published ? (
                  <>
                    <CheckCircle2 size={14} className="mr-1" />
                    {t('projects.published')}
                  </>
                ) : (
                  <>
                    <Send size={14} className="mr-1" />
                    {t('projects.publish')}
                  </>
                )}
              </Button>
            </div>
          </Card>
        ))}
      </div>

      <Modal
        isOpen={isTzModalOpen}
        onClose={() => setIsTzModalOpen(false)}
        title={t('projects.tzModal.title')}
        footer={
          <>
            <Button variant="secondary" onClick={() => setIsTzModalOpen(false)}>
              {t('projects.tzModal.close')}
            </Button>
            <Button onClick={handleSaveTz}>
              <CheckCircle2 size={16} className="mr-2" />
              {t('projects.tzModal.save')}
            </Button>
          </>
        }
      >
        <div className="space-y-4">
          <div className="p-3 bg-blue-50 rounded-lg border border-blue-200 text-sm text-blue-800 flex items-start gap-2">
            <Eye size={16} className="mt-0.5 shrink-0" />
            <div>
              <p className="font-semibold mb-1">
                {locale === 'ru' ? 'Предпросмотр ТЗ' : 'TZ Preview'}
              </p>
              <p>
                {t('projects.tzModal.info')}
              </p>
            </div>
          </div>
          <textarea
            className="w-full h-80 p-4 border border-border rounded-lg font-mono text-sm focus:outline-none focus:ring-2 focus:ring-primary-light leading-relaxed"
            value={tzContent}
            onChange={(e) => setTzContent(e.target.value)}
          />
        </div>
      </Modal>
    </div>
  )
}